local addonName, ns = ...

ns.CLASSES = {
	WARRIOR = 1,
	PALADIN = 2,
	HUNTER = 3,
	ROGUE = 4,
	PRIEST = 5,
	SHAMAN = 7,
	MAGE = 8,
	WARLOCK = 9,
	DRUID = 11,
}

-- Styles de jeu par classe. Druide hybrid = switch automatique caster / chat / ours.
ns.CLASS_ROLES = {
	WARRIOR = { "damage", "tank" },
	PALADIN = { "damage", "tank", "heal" },
	HUNTER = { "range", "melee" },
	ROGUE = { "damage" },
	PRIEST = { "damage", "heal", "disc" },
	SHAMAN = { "caster", "melee", "heal" },
	MAGE = { "damage" },
	WARLOCK = { "damage" },
	DRUID = { "hybrid", "heal", "tank" },
}

ns.COMBAT_MODES = { "auto", "single", "aoe", "burst" }

-- Couleurs officielles WoW, lues en dur (Forever peut cacher RAID_CLASS_COLORS).
ns.CLASS_COLORS = {
	WARRIOR = { 0.78, 0.61, 0.43 },
	PALADIN = { 0.96, 0.55, 0.73 },
	HUNTER = { 0.67, 0.83, 0.45 },
	ROGUE = { 1.00, 0.96, 0.41 },
	PRIEST = { 1.00, 1.00, 1.00 },
	SHAMAN = { 0.00, 0.44, 0.87 },
	MAGE = { 0.25, 0.78, 0.92 },
	WARLOCK = { 0.58, 0.51, 0.79 },
	DRUID = { 1.00, 0.49, 0.04 },
}

ns.CLASS_BY_ID = {
	[1] = "WARRIOR",
	[2] = "PALADIN",
	[3] = "HUNTER",
	[4] = "ROGUE",
	[5] = "PRIEST",
	[7] = "SHAMAN",
	[8] = "MAGE",
	[9] = "WARLOCK",
	[11] = "DRUID",
}

ns.COLOR_DEFAULTS = {
	next = { 1, 1, 1 },
	heal = { 0.15, 1, 0.28 },
	def = { 0.2, 0.55, 1 },
	weapon = { 1, 0.12, 0.08 },
	range = { 0.88, 0.06, 0.06 },
}

function ns.Color(key)
	local pack = ns.db and ns.db.colors and ns.db.colors[key]
	if type(pack) == "table" then
		local r, g, b = tonumber(pack[1]), tonumber(pack[2]), tonumber(pack[3])
		if r then
			return r, g or 0, b or 0
		end
	end
	pack = ns.COLOR_DEFAULTS[key] or ns.COLOR_DEFAULTS.next
	return pack[1], pack[2], pack[3]
end

ns.CLASS_DAMAGE_ICON = {
	WARRIOR = "melee",
	PALADIN = "melee",
	HUNTER = "range",
	ROGUE = "melee",
	PRIEST = "caster",
	SHAMAN = "caster",
	MAGE = "caster",
	WARLOCK = "caster",
	DRUID = "caster",
}

ns.CLASS_SPELL = {
	WARRIOR = "Warrior",
	PALADIN = "Paladin",
	HUNTER = "Hunter",
	ROGUE = "Rogue",
	PRIEST = "Priest",
	SHAMAN = "Shaman",
	MAGE = "Mage",
	WARLOCK = "Warlock",
	DRUID = "Druid",
}

-- Raciaux Classic + Éolides. Air Walk (1259416) et passifs (Béni par le vent, Perspicacité) absents.
-- 95 = Éolide de l'Ordre suprême (Alliance) — ligne tellurique
-- 96 = Éolide sculpte-vents (Horde) — vue céleste
ns.RACIALS = {
	{ key = "Perception", id = 20600, races = { 1 }, opt = { combat = true } },
	{ key = "BloodFury", id = 20572, races = { 2 }, opt = { hostile = true }, on = true },
	{ key = "Stoneform", id = 20594, races = { 3 }, opt = { combat = true, hp = 70 }, defensive = true },
	{ key = "Shadowmeld", id = 20580, races = { 4 }, opt = { nobuff = true }, defensive = true },
	{ key = "WilloftheForsaken", id = 7744, races = { 5 }, defensive = true },
	{ key = "WarStomp", id = 20549, races = { 6 }, opt = { hostile = true } },
	{ key = "EscapeArtist", id = 20589, races = { 7 }, defensive = true },
	{ key = "Berserking", id = 20554, races = { 8 }, opt = { hostile = true }, on = true },
	{ key = "LeyLine", id = 1259705, races = { 95 }, factions = { "Alliance" }, opt = { hostile = true }, defensive = true },
	{ key = "SkyView", id = 1259686, races = { 96 }, factions = { "Horde" } },
	{ key = "WillToSurvive", id = 1259810, races = { 1 }, defensive = true },
	{ key = "ElunesLight", id = 1259680, races = { 4 }, opt = { hostile = true }, on = true },
	{ key = "Eureka", id = 1259813, races = { 7 }, opt = { hostile = true }, on = true },
	{ key = "ShatterCurse", id = 1259681, races = { 2 }, defensive = true },
	{ key = "Cannibalize", id = 20577, races = { 5 }, opt = { nocombat = true } },
	{ key = "RapidRegeneration", id = 1259682, races = { 8 }, opt = { combat = true, hp = 50 }, defensive = true },
}

ns.INTERRUPTS = {
	WARRIOR = 6552, -- Pummel
	ROGUE = 1766, -- Kick
	SHAMAN = 8042, -- Earth Shock (Era interrupt)
	MAGE = 2139, -- Counterspell
	PRIEST = 15487, -- Silence (talent)
}

ns.PURGES = {
	SHAMAN = 370, -- Purge
	PRIEST = 527, -- Dispel Magic
	MAGE = 30449, -- Spellsteal (may be absent)
}

-- Dispel perso : maladie / poison / malédiction / magie sur le joueur.
ns.CLEANSE = {
	PALADIN = {
		{ id = 4987, types = { "Magic", "Disease", "Poison" } }, -- Cleanse
		{ id = 1152, types = { "Disease", "Poison" } }, -- Purify
	},
	PRIEST = {
		{ id = 552, types = { "Disease" } }, -- Abolish Disease
		{ id = 528, types = { "Disease" } }, -- Cure Disease
		{ id = 527, types = { "Magic" } }, -- Dispel Magic (self)
	},
	SHAMAN = {
		{ id = 2870, types = { "Disease" } }, -- Cure Disease
		{ id = 526, types = { "Poison" } }, -- Cure Poison
	},
	DRUID = {
		{ id = 2893, types = { "Poison" } }, -- Abolish Poison
		{ id = 8946, types = { "Poison" } }, -- Cure Poison
		{ id = 2782, types = { "Curse" } }, -- Remove Curse
	},
	MAGE = {
		{ id = 475, types = { "Curse" } }, -- Remove Lesser Curse
	},
}

-- Enchantements d'arme Forever (lab 1.60.1) — durée 60 min, IDs = GetWeaponEnchantInfo 4e valeur.
ns.WEAPON_BUFFS = {
	SHAMAN = {
		{
			key = "Windfury",
			id = 8232,
			duration = 3600,
			ranks = { 8232, 8235, 10486, 16362, 439431, 461636 },
			enchants = { 283, 284, 525, 1669, 7569 },
			match = {
				"furie-des-vents",
				"furie des vents",
				"windfury",
				"croc-croc",
				"croc croc",
				"windzorn",
				"viento furioso",
				"неистовство ветра",
				"fúria dos ventos",
				"furia dos ventos",
				"furia del vento",
				"질풍",
				"风怒",
				"風怒",
			},
		},
		{
			key = "Flametongue",
			id = 8024,
			duration = 3600,
			ranks = { 8024, 8027, 8030, 16339, 16341, 16342, 461634 },
			enchants = { 3, 4, 5, 523, 1665, 1666, 7567 },
			match = {
				"langue de feu",
				"flametongue",
				"flammenzunge",
				"lengua de fuego",
				"язык пламени",
				"língua de fogo",
				"lingua de fogo",
				"lingua del fuoco",
				"화염",
				"火舌",
			},
		},
		{
			key = "Rockbiter",
			id = 8017,
			duration = 3600,
			ranks = { 8017, 8018, 8019, 10399, 16314, 16315, 16316, 461635 },
			enchants = { 1, 6, 29, 503, 504, 683, 1663, 1664, 7568 },
			match = {
				"croque-roc",
				"croque roc",
				"rockbiter",
				"felsbeisser",
				"arma de piedra",
				"каменн",
				"pedra",
				"roccia",
				"대지의",
				"石化",
				"石化武器",
			},
		},
		{
			key = "Frostbrand",
			id = 8033,
			duration = 3600,
			ranks = { 8033, 8038, 10456, 16355, 16356, 461633 },
			enchants = { 2, 12, 524, 1667, 1668, 7566 },
			match = {
				"arme de givre",
				"frostbrand",
				"frostwaffe",
				"arma de escarcha",
				"ледяное",
				"arma gélida",
				"arma gelida",
				"tundra",
				"냉기",
				"冰封",
			},
		},
	},
	ROGUE = {
		{
			key = "InstantPoison",
			id = 8679,
			duration = 1800,
			enchants = { 323, 324, 325, 623, 624, 625 },
			match = { "poison instantané", "instant poison", "sofort wirkendes gift", "veneno instantáneo", "быстродействующий яд", "veneno instantâneo", "veleno istantaneo", "순간 효과 독", "速效毒药", "速效毒藥" },
		},
		{
			key = "DeadlyPoison",
			id = 2823,
			duration = 1800,
			enchants = { 7, 8, 626, 627, 2630 },
			match = { "poison mortel", "deadly poison", "tödliches gift", "veneno mortal", "смертельный яд", "veleno mortale", "맹독", "致命毒药", "致命毒藥" },
		},
		{
			key = "CripplingPoison",
			id = 3408,
			duration = 1800,
			enchants = { 22, 603 },
			match = { "poison affaiblissant", "crippling", "verkrüppelndes gift", "veneno entorpecedor", "калечащий яд", "veneno debilitante", "veleno stordente", "신경 마비 독", "致残毒药", "致殘毒藥" },
		},
		{
			key = "WoundPoison",
			id = 13219,
			duration = 1800,
			enchants = { 703, 704, 705, 706 },
			match = { "poison douloureux", "wound poison", "wundgift", "veneno hiriente", "ранящий яд", "veneno ferino", "veleno ferisce", "상처 독", "致伤毒药", "致傷毒藥" },
		},
		{
			key = "MindNumbingPoison",
			id = 5761,
			duration = 1800,
			enchants = { 23, 35, 643 },
			match = { "distraction mentale", "mind-numbing", "mind numbing", "gedankenbenebelndes gift", "veneno de aturdimiento mental", "дурманящий яд", "veneno entorpecente", "veleno stordisci mente", "정신 마취 독", "麻痹毒药", "麻痹毒藥" },
		},
	},
	WARLOCK = {
		{
			key = "Firestone",
			id = 6366,
			duration = 7200,
			enchants = { 1803, 1823, 1824, 1825 },
			match = { "pierre de feu", "firestone", "feuerstein", "piedra de fuego", "камень огня", "pedra de fogo", "pietra del fuoco", "화염석", "火焰石" },
		},
		{
			key = "Spellstone",
			id = 2362,
			duration = 7200,
			enchants = { 8059, 8060, 8061 },
			match = { "pierre de sort", "spellstone", "zauberstein", "piedra de hechizo", "камень чар", "pedra mágica", "pietra della magia", "주문석", "法术石", "法術石" },
		},
	},
}

ns.WEAPON_BUFF_IDS = {}
ns.WEAPON_ENCHANT_IDS = {}
for _, list in pairs(ns.WEAPON_BUFFS) do
	for _, entry in ipairs(list) do
		ns.WEAPON_BUFF_IDS[entry.id] = entry
		if entry.ranks then
			for _, rankID in ipairs(entry.ranks) do
				ns.WEAPON_BUFF_IDS[rankID] = entry
			end
		end
		if entry.enchants then
			for _, enchID in ipairs(entry.enchants) do
				ns.WEAPON_ENCHANT_IDS[enchID] = entry
			end
		end
	end
end

-- IDs Forever / Classic Era (lab 1.60.1)
ns.Spell = {
	Druid = {
		Wrath = 5176,
		Moonfire = 8921,
		Starfire = 2912,
		FaerieFire = 770,
		InsectSwarm = 5570,
		Hurricane = 16914,
		MarkoftheWild = 1126,
		Thorns = 467,
		HealingTouch = 5185,
		Regrowth = 8936,
		Rejuvenation = 774,
		Barkskin = 22812,
		NaturesGrasp = 16689,
		BearForm = 5487,
		CatForm = 768,
		Maul = 6807,
		Swipe = 779,
		Claw = 1082,
		Rake = 1822,
		Rip = 1079,
		Shred = 5221,
		FerociousBite = 22568,
		Moonkin = 24858,
		TigersFury = 5217,
		NaturesSwiftness = 17116,
		Tranquility = 740,
		FaerieFireFeral = 16857,
		DemoralizingRoar = 99,
		Growl = 6795,
		Bash = 5211,
		Ravage = 6785,
		Prowl = 5215,
		Swiftmend = 18562,
		DireBear = 9634,
		Enrage = 5229,
		Innervate = 29166,
		FrenziedRegen = 22842,
		FeralCharge = 16979,
		FeralChargeCat = 414924,
		Lacerate = 414644,
		MangleCat = 407995,
		MangleBear = 407995,
		Berserk = 417141,
		WildGrowth = 408120,
	},
	Paladin = {
		HolyLight = 635,
		FlashofLight = 19750,
		SealRighteousness = 20154,
		SealFury = 20163,
		SealCommand = 20375,
		SealCrusader = 21082,
		Judgement = 20271,
		JudgementoftheCrusader = 21183,
		JudgementofJustice = 20184,
		JudgementofLight = 20185,
		JudgementofWisdom = 20186,
		BlessingMight = 19740,
		BlessingWisdom = 19742,
		BlessingKings = 20217,
		Consecration = 26573,
		HammerofJustice = 853,
		HammerofWrath = 24275,
		Exorcism = 879,
		DevotionAura = 465,
		RetributionAura = 7294,
		DivineProtection = 498,
		DivineShield = 642,
		LayonHands = 633,
		RighteousFury = 25780,
		HolyWrath = 2812,
		HolyShock = 20473,
		HolyShield = 20925,
		SealLight = 20165,
		SealWisdom = 20166,
		SealJustice = 20164,
		ConcentrationAura = 19746,
		SanctityAura = 20218,
		CrusaderStrike = 678,
		BlessingSalvation = 1038,
		BlessingLight = 19977,
		BlessingSanctuary = 20911,
		FireResistAura = 19891,
		FrostResistAura = 19888,
		ShadowResistAura = 19876,
		HolyStrike = 1310903,
		LightsVigil = 1310911,
		VoiceOfTruth = 1310897,
		TemplarsBulwark = 1311015,
		SwiftJudgement = 1310994,
	},
	Warrior = {
		HeroicStrike = 78,
		BattleShout = 6673,
		Charge = 100,
		Rend = 772,
		ThunderClap = 6343,
		Overpower = 7384,
		Execute = 5308,
		MortalStrike = 12294,
		Bloodthirst = 23881,
		Whirlwind = 1680,
		Hamstring = 1715,
		SunderArmor = 7386,
		Revenge = 6572,
		ShieldSlam = 23922,
		ShieldBlock = 2565,
		Taunt = 355,
		LastStand = 12975,
		ShieldWall = 871,
		Bloodrage = 2687,
		Pummel = 6552,
		Cleave = 845,
		Recklessness = 1719,
		SweepingStrikes = 12292,
		DeathWish = 12328,
		BerserkerRage = 18499,
		Intercept = 20252,
		Slam = 1464,
		DemoralizingShout = 1160,
		Retaliation = 20230,
		Disarm = 676,
		ShieldBash = 72,
		MockingBlow = 694,
		PiercingHowl = 12323,
		SpearingStrike = 1310222,
		VictoryRush = 34428,
	},
	Hunter = {
		RaptorStrike = 2973,
		AutoShot = 75,
		SerpentSting = 1978,
		ArcaneShot = 3044,
		AimedShot = 19434,
		MultiShot = 2643,
		HuntersMark = 1130,
		AspectHawk = 13165,
		ConcussiveShot = 5116,
		MendPet = 136,
		CallPet = 883,
		WingClip = 2974,
		FeignDeath = 5384,
		Deterrence = 19263,
		AspectMonkey = 13163,
		RapidFire = 3045,
		Volley = 1510,
		BestialWrath = 19574,
		MongooseBite = 1495,
		Counterattack = 19306,
		Intimidation = 19577,
		ViperSting = 3034,
		ScorpidSting = 3043,
		AspectWild = 20043,
		AspectCheetah = 5118,
		AspectPack = 13159,
		AspectBeast = 13161,
		TrueshotAura = 19506,
		WyvernSting = 19386,
		Disengage = 781,
		StriderKick = 1317257,
		SummonHawk = 1293241,
		SniperShot = 1310662,
		ScatterShot = 19503,
		HydraShot = 1293020,
		Lacerate = 1317260,
		TranquilizingShot = 19801,
		EnchantedFlare = 1221404,
		Flare = 1543,
		DistractingShot = 20736,
	},
	Rogue = {
		SinisterStrike = 1752,
		Eviscerate = 2098,
		Stealth = 1784,
		Backstab = 53,
		Gouge = 1776,
		Kick = 1766,
		SliceandDice = 5171,
		Garrote = 703,
		Ambush = 8676,
		Rupture = 1943,
		Evasion = 5277,
		Sprint = 2983,
		BladeFlurry = 13877,
		AdrenalineRush = 13750,
		ColdBlood = 14177,
		Hemorrhage = 16511,
		ExposeArmor = 8647,
		GhostlyStrike = 14278,
		Riposte = 14251,
		CheapShot = 1833,
		KidneyShot = 408,
		Vanish = 1856,
		Feint = 1966,
		Premeditation = 14183,
		Mutilate = 1329,
		Venom = 1311401,
		Preparation = 14185,
	},
	Priest = {
		Smite = 585,
		LesserHeal = 2050,
		ShadowWordPain = 589,
		PowerWordShield = 17,
		Renew = 139,
		MindBlast = 8092,
		InnerFire = 588,
		Heal = 2054,
		FlashHeal = 2061,
		HolyFire = 14914,
		PsychicScream = 8122,
		Fade = 586,
		WeakenedSoul = 6788,
		HolyNova = 15237,
		InnerFocus = 14751,
		PrayerofHealing = 596,
		MindFlay = 15407,
		GreaterHeal = 2060,
		Shadowform = 15473,
		VampiricEmbrace = 15286,
		DivineSpirit = 14752,
		PowerWordFortitude = 1243,
		PowerInfusion = 10060,
		DevouringPlague = 2944,
		ManaBurn = 8129,
		ShadowProtection = 976,
		Silence = 15487,
		Chastise = 1277331,
		ConfoundingFlash = 1277455,
		DarkSacrifice = 1277324,
		DivineGrace = 1277370,
		ContingencyPlan = 1277456,
		Penance = 47540,
		PrayerofMending = 33076,
		BindingHeal = 32546,
		ShadowWordDeath = 32379,
		-- Wand auto-repeat (General tab). Resolved by name like every other spell.
		Shoot = 5019,
	},
	Shaman = {
		LightningBolt = 403,
		HealingWave = 331,
		Rockbiter = 8017,
		EarthShock = 8042,
		LightningShield = 324,
		FlameShock = 8050,
		SearingTotem = 3599,
		LesserHealingWave = 8004,
		FrostShock = 8056,
		ChainLightning = 421,
		Stormstrike = 17364,
		Purge = 370,
		Windfury = 8232,
		Flametongue = 8024,
		Frostbrand = 8033,
		Stoneclaw = 5730,
		GroundingTotem = 8177,
		FireNova = 408341,
		MagmaTotem = 8190,
		ElementalMastery = 16166,
		NaturesSwiftness = 16188,
		ChainHeal = 1064,
		StrengthofEarth = 8075,
		Stoneskin = 8071,
		HealingStream = 5394,
		ManaSpring = 5675,
		WindfuryTotem = 8512,
		GraceofAir = 8835,
		TremorTotem = 8143,
		CalloftheElements = 66842,
		CalloftheAncestors = 66843,
		CalloftheSpirits = 66844,
		TotemicRecall = 36936,
		LavaBurst = 408490,
		Riptide = 408521,
		WaterShield = 408510,
		TotemicProjection = 437009,
	},
	Mage = {
		Fireball = 133,
		FrostArmor = 168,
		ArcaneIntellect = 1459,
		Frostbolt = 116,
		FireBlast = 2136,
		ArcaneMissiles = 5143,
		FrostNova = 122,
		ArcaneExplosion = 1449,
		Counterspell = 2139,
		Blink = 1953,
		ConeofCold = 120,
		Pyroblast = 11366,
		Flamestrike = 2120,
		Scorch = 2948,
		FireVulnerability = 22959,
		WintersChill = 12579,
		IceArmor = 7302,
		MageArmor = 6117,
		Evocation = 12051,
		IceBlock = 11958,
		IceBarrier = 11426,
		Blizzard = 10,
		Combustion = 11129,
		PresenceofMind = 12043,
		ArcanePower = 12042,
		BlastWave = 11113,
		ManaShield = 1463,
		FireWard = 543,
		FrostWard = 6143,
		AmplifyMagic = 1008,
		DampenMagic = 604,
		FrostfireBolt = 401502,
		IceLance = 400640,
		ArcaneBlast = 400574,
	},
	Warlock = {
		ShadowBolt = 686,
		Immolate = 348,
		DemonSkin = 687,
		SummonImp = 688,
		Corruption = 172,
		LifeTap = 1454,
		CurseofAgony = 980,
		SummonVoidwalker = 697,
		DrainLife = 689,
		Fear = 5782,
		SearingPain = 5676,
		RainofFire = 5740,
		Shadowburn = 17877,
		Conflagrate = 17962,
		DeathCoil = 6789,
		Hellfire = 1949,
		DemonArmor = 706,
		SoulFire = 6353,
		SiphonLife = 18265,
		DrainSoul = 1120,
		CurseofElements = 1490,
		CurseofShadow = 17862,
		HowlofTerror = 5484,
		SummonSuccubus = 712,
		SummonFelhunter = 691,
		ShadowWard = 6229,
		UnendingBreath = 5697,
		DetectInvisibility = 132,
		Incinerate = 412758,
		BaneofHavoc = 80240,
		Wrack = 1311501,
		SummonIncubus = 713,
	},
}

-- Noms de grimoire, 11 locales client. Resolve teste la langue du jeu d'abord, puis les autres.
local function spellNames(map)
	if map.esMX == nil then
		map.esMX = map.esES
	end
	return map
end

ns.SPELL_NAME_HINT = {
	-- Wand "Shoot" (priest / mage / warlock). Name fallback if Forever remaps 5019.
	[5019] = spellNames({
		enUS = "Shoot",
		frFR = "Tir",
		deDE = "Schießen",
		esES = "Disparar",
		ruRU = "Выстрел",
		zhCN = "射击",
		zhTW = "射擊",
		ptBR = "Atirar",
		itIT = "Spara",
		koKR = "사격",
	}),
	[34428] = spellNames({
		enUS = "Victory Rush",
		frFR = "Ivresse de la victoire",
		deDE = "Siegesrausch",
		esES = { "Ímpetu victorioso", "Acometida victoriosa" },
		ruRU = "Победный раж",
		zhCN = "乘胜追击",
		zhTW = "勝利衝擊",
		ptBR = "Ímpeto da Vitória",
		itIT = "Brivido della Vittoria",
		koKR = "승리의 돌진",
	}),
	[1310222] = spellNames({
		enUS = "Spearing Strike",
		frFR = "Frappe transperçante",
		deDE = "Speerstoß",
		esES = "Golpe de lanza",
		ruRU = "Пронзающий удар",
		zhCN = "穿刺打击",
		zhTW = "穿刺打擊",
		ptBR = "Golpe Perfurante",
		itIT = "Assalto Trafitto",
		koKR = "창격",
	}),
	[1310903] = spellNames({
		enUS = "Holy Strike",
		frFR = "Frappe sacrée",
		deDE = "Heiliger Stoß",
		esES = "Golpe sagrado",
		ruRU = "Священный удар",
		zhCN = "神圣打击",
		zhTW = "神聖打擊",
		ptBR = "Golpe Sagrado",
		itIT = "Assalto Sacro",
		koKR = "신성한 일격",
	}),
	[1310911] = spellNames({
		enUS = "Light's Vigil",
		frFR = "Veille de la Lumière",
		deDE = "Wacht des Lichts",
		esES = "Vigilia de la Luz",
		ruRU = "Бдение Света",
		zhCN = "圣光守夜",
		zhTW = "聖光守夜",
		ptBR = "Vigília da Luz",
		itIT = "Veglia della Luce",
		koKR = "빛의 경계",
	}),
	[1310897] = spellNames({
		enUS = "Voice of Truth",
		frFR = "Voix de la vérité",
		deDE = "Stimme der Wahrheit",
		esES = "Voz de la verdad",
		ruRU = "Голос истины",
		zhCN = "真理之声",
		zhTW = "真理之聲",
		ptBR = "Voz da Verdade",
		itIT = "Voce della Verità",
		koKR = "진실의 목소리",
	}),
	[1311015] = spellNames({
		enUS = "Templar's Bulwark",
		frFR = "Rempart du templier",
		deDE = "Bollwerk des Templers",
		esES = "Baluarte del templario",
		ruRU = "Оплот храмовника",
		zhCN = "圣殿骑士壁垒",
		zhTW = "聖殿騎士壁壘",
		ptBR = "Baluarte do Templário",
		itIT = "Baluardo del Templare",
		koKR = "성기사의 보루",
	}),
	[1310994] = spellNames({
		enUS = "Swift Judgement",
		frFR = "Jugement rapide",
		deDE = "Schnelles Urteil",
		esES = "Sentencia rápida",
		ruRU = "Быстрый суд",
		zhCN = "迅捷审判",
		zhTW = "迅捷審判",
		ptBR = "Julgamento Célere",
		itIT = "Giudizio Rapido",
		koKR = "신속한 심판",
	}),
	[21183] = spellNames({
		enUS = "Judgement of the Crusader",
		frFR = "Jugement du croisé",
		deDE = "Urteil des Kreuzfahrers",
		esES = "Sentencia del Cruzado",
		ruRU = "Правосудие крестоносца",
		zhCN = "十字军审判",
		zhTW = "十字軍審判",
		ptBR = "Julgamento do Cruzado",
		itIT = "Giudizio del Crociato",
		koKR = "성전사의 심판",
	}),
	[20184] = spellNames({
		enUS = "Judgement of Justice",
		frFR = "Jugement de justice",
		deDE = "Urteil der Gerechtigkeit",
		esES = "Sentencia de justicia",
		ruRU = "Правосудие справедливости",
		zhCN = "公正审判",
		zhTW = "公正審判",
		ptBR = "Julgamento da Justiça",
		itIT = "Giudizio della Giustizia",
		koKR = "정의의 심판",
	}),
	[20185] = spellNames({
		enUS = "Judgement of Light",
		frFR = "Jugement de lumière",
		deDE = "Urteil des Lichts",
		esES = "Sentencia de Luz",
		ruRU = "Правосудие света",
		zhCN = "光明审判",
		zhTW = "光明審判",
		ptBR = "Julgamento da Luz",
		itIT = "Giudizio della Luce",
		koKR = "빛의 심판",
	}),
	[20186] = spellNames({
		enUS = "Judgement of Wisdom",
		frFR = "Jugement de sagesse",
		deDE = "Urteil der Weisheit",
		esES = "Sentencia de sabiduría",
		ruRU = "Правосудие мудрости",
		zhCN = "智慧审判",
		zhTW = "智慧審判",
		ptBR = "Julgamento da Sabedoria",
		itIT = "Giudizio della Saggezza",
		koKR = "지혜의 심판",
	}),
	[22959] = spellNames({
		enUS = "Fire Vulnerability",
		frFR = "Vulnérabilité au Feu",
		deDE = "Feuervulnerabilität",
		esES = "Vulnerabilidad de Fuego",
		ruRU = "Уязвимость к огню",
		zhCN = "火焰易伤",
		zhTW = "火焰易傷",
		ptBR = "Vulnerabilidade a Fogo",
		itIT = "Vulnerabilità al Fuoco",
		koKR = "화염 취약",
	}),
	[12579] = spellNames({
		enUS = "Winter's Chill",
		frFR = "Froid hivernal",
		deDE = "Winterkälte",
		esES = "Escalofrío invernal",
		ruRU = "Зимняя стужа",
		zhCN = "深冬之寒",
		zhTW = "深冬之寒",
		ptBR = "Calafrio de Inverno",
		itIT = "Gelo Invernale",
		koKR = "혹한의 추위",
	}),
	[19801] = spellNames({
		enUS = "Tranquilizing Shot",
		frFR = "Tir tranquillisant",
		deDE = "Einlullender Schuss",
		esES = "Disparo tranquilizante",
		ruRU = "Усмиряющий выстрел",
		zhCN = "宁神射击",
		zhTW = "寧神射擊",
		ptBR = "Tiro Tranquilizante",
		itIT = "Tiro Tranquillizzante",
		koKR = "평정의 사격",
	}),
	[1221404] = spellNames({
		enUS = "Enchanted Flare",
		frFR = "Fusée éclairante enchantée",
		deDE = "Verzaubertes Leuchtfeuer",
		esES = "Bengala encantada",
		ruRU = "Зачарованная сигнальная ракета",
		zhCN = "魔化照明弹",
		zhTW = "魔化照明彈",
		ptBR = "Sinalizador Encantado",
		itIT = "Bengala Incantata",
		koKR = "마법 섬광탄",
	}),
	[1543] = spellNames({
		enUS = "Flare",
		frFR = "Fusée éclairante",
		deDE = "Leuchtfeuer",
		esES = "Bengala",
		ruRU = "Сигнальная ракета",
		zhCN = "照明弹",
		zhTW = "照明彈",
		ptBR = "Sinalizador",
		itIT = "Bengala",
		koKR = "섬광탄",
	}),
	[20736] = spellNames({
		enUS = "Distracting Shot",
		frFR = "Trait provocateur",
		deDE = "Ablenkender Schuss",
		esES = "Disparo de distracción",
		ruRU = "Отвлекающий выстрел",
		zhCN = "扰乱射击",
		zhTW = "擾亂射擊",
		ptBR = "Tiro Distrativo",
		itIT = "Tiro Disturbo",
		koKR = "견제 사격",
	}),
	[14185] = spellNames({
		enUS = "Preparation",
		frFR = "Préparation",
		deDE = "Vorbereitung",
		esES = "Preparación",
		ruRU = "Подготовка",
		zhCN = "伺机待发",
		zhTW = "準備就緒",
		ptBR = "Preparação",
		itIT = "Preparazione",
		koKR = "마음가짐",
	}),
	[1317257] = spellNames({
		enUS = "Strider Kick",
		frFR = "Coup de grand-marcheur",
		deDE = "Schreitertritt",
		esES = "Patada de zancudo",
		ruRU = "Удар долгонога",
		zhCN = "陆行鸟踢",
		zhTW = "陸行鳥踢",
		ptBR = "Chute do Moa",
		itIT = "Calcio dello Strider",
		koKR = "타조 발차기",
	}),
	[1293241] = spellNames({
		enUS = "Summon Hawk",
		frFR = "Invocation d'un faucon",
		deDE = "Habicht beschwören",
		esES = "Invocar halcón",
		ruRU = "Призыв ястреба",
		zhCN = "召唤鹰",
		zhTW = "召喚鷹",
		ptBR = "Evocar Falcão",
		itIT = "Evoca Falco",
		koKR = "매 소환",
	}),
	[1310662] = spellNames({
		enUS = "Sniper Shot",
		frFR = "Tir de sniper",
		deDE = "Heckenschützenschuss",
		esES = "Disparo de francotirador",
		ruRU = "Снайперский выстрел",
		zhCN = "狙击射击",
		zhTW = "狙擊射擊",
		ptBR = "Tiro de Franco-atirador",
		itIT = "Tiro da Cecchino",
		koKR = "저격 사격",
	}),
	[19503] = spellNames({
		enUS = "Scatter Shot",
		frFR = "Flèche de dispersion",
		deDE = "Streuschuss",
		esES = "Disparo de dispersión",
		ruRU = "Дезориентирующий выстрел",
		zhCN = "驱散射击",
		zhTW = "驅散射擊",
		ptBR = "Tiro de Dispersão",
		itIT = "Tiro Dispersante",
		koKR = "산탄 사격",
	}),
	[1293020] = spellNames({
		enUS = "Hydra Shot",
		frFR = "Tir d'hydre",
		deDE = "Hydraschuss",
		esES = "Disparo de hidra",
		ruRU = "Выстрел гидры",
		zhCN = "多头蛇射击",
		zhTW = "多頭蛇射擊",
		ptBR = "Tiro da Hidra",
		itIT = "Tiro dell'Idra",
		koKR = "히드라 사격",
	}),
	[1317260] = spellNames({
		enUS = "Lacerate",
		frFR = "Lacérer",
		deDE = "Aufschlitzen",
		esES = "Lacerar",
		ruRU = "Разорвать",
		zhCN = "割伤",
		zhTW = "割裂",
		ptBR = "Lacerar",
		itIT = "Lacerazione",
		koKR = "찢어발기기",
	}),
	[1329] = spellNames({
		enUS = "Mutilate",
		frFR = "Estropier",
		deDE = "Verstümmeln",
		esES = "Mutilar",
		ruRU = "Расправа",
		zhCN = "毁伤",
		zhTW = "截肢",
		ptBR = "Mutilar",
		itIT = "Mutilazione",
		koKR = "절단",
	}),
	[1311401] = spellNames({
		enUS = "Venom",
		frFR = "Venin",
		deDE = "Gift",
		esES = "Veneno",
		ruRU = "Яд",
		zhCN = "毒液",
		zhTW = "毒液",
		ptBR = "Veneno",
		itIT = "Veleno",
		koKR = "맹독",
	}),
	[1277331] = spellNames({
		enUS = "Chastise",
		frFR = "Châtiment",
		deDE = "Züchtigung",
		esES = "Castigar",
		ruRU = "Порицание",
		zhCN = "惩戒",
		zhTW = "懲戒",
		ptBR = "Castigar",
		itIT = "Castigo",
		koKR = "징벌",
	}),
	[1277455] = spellNames({
		enUS = "Confounding Flash",
		frFR = "Éclair déroutant",
		deDE = "Verwirrendes Aufblitzen",
		esES = "Destello desconcertante",
		ruRU = "Сбивающая вспышка",
		zhCN = "迷惑闪光",
		zhTW = "迷惑閃光",
		ptBR = "Clarão Confuso",
		itIT = "Lampo Sconcertante",
		koKR = "혼란의 섬광",
	}),
	[1277324] = spellNames({
		enUS = "Dark Sacrifice",
		frFR = "Sacrifice sombre",
		deDE = "Dunkles Opfer",
		esES = "Sacrificio oscuro",
		ruRU = "Темная жертва",
		zhCN = "黑暗献祭",
		zhTW = "黑暗獻祭",
		ptBR = "Sacrifício Sombrio",
		itIT = "Sacrificio Oscuro",
		koKR = "어둠의 희생",
	}),
	[1277370] = spellNames({
		enUS = "Divine Grace",
		frFR = "Grâce divine",
		deDE = "Göttliche Gnade",
		esES = "Gracia divina",
		ruRU = "Божественная милость",
		zhCN = "神圣恩典",
		zhTW = "神聖恩典",
		ptBR = "Graça Divina",
		itIT = "Grazia Divina",
		koKR = "천상의 은총",
	}),
	[1277456] = spellNames({
		enUS = { "Contingency Plan", "Emergency Plan" },
		frFR = { "Plan de contingence", "Plan d'urgence" },
		deDE = "Notfallplan",
		esES = "Plan de contingencia",
		ruRU = "Запасной план",
		zhCN = "应急计划",
		zhTW = "應變計畫",
		ptBR = "Plano de Contingência",
		itIT = "Piano di Emergenza",
		koKR = "비상 계획",
	}),
	[47540] = spellNames({
		enUS = "Penance",
		frFR = "Pénitence",
		deDE = "Sühne",
		esES = "Penitencia",
		ruRU = "Исповедь",
		zhCN = "苦修",
		zhTW = "苦修",
		ptBR = "Penitência",
		itIT = "Penitenza",
		koKR = "고행",
	}),
	[33076] = spellNames({
		enUS = "Prayer of Mending",
		frFR = "Prière de guérison",
		deDE = "Gebet der Besserung",
		esES = "Rezo de alivio",
		ruRU = "Молитва восстановления",
		zhCN = "愈合祷言",
		zhTW = "癒合禱言",
		ptBR = "Prece da Restauração",
		itIT = "Preghiera di Guarigione",
		koKR = "회복의 기원",
	}),
	[32546] = spellNames({
		enUS = "Binding Heal",
		frFR = "Soins de lien",
		deDE = "Verbindende Heilung",
		esES = "Sanación conjunta",
		ruRU = "Связующее исцеление",
		zhCN = "联结治疗",
		zhTW = "束縛治療",
		ptBR = "Cura Vinculada",
		itIT = "Cura Legante",
		koKR = "결속의 치유",
	}),
	[32379] = spellNames({
		enUS = { "Shadow Word: Death", "Shadow Word:Death" },
		frFR = { "Mot de l'ombre : Mort", "Mot de l'ombre: Mort" },
		deDE = "Schattenwort: Tod",
		esES = { "Palabra de las Sombras: muerte", "Palabra de las Sombras: Muerte" },
		ruRU = "Слово Тьмы: Смерть",
		zhCN = "暗言术：灭",
		zhTW = "暗言術:死",
		ptBR = "Palavra Sombria: Morte",
		itIT = "Parola d'Ombra: Morte",
		koKR = "어둠의 권능: 죽음",
	}),
	[66842] = spellNames({
		enUS = "Call of the Elements",
		frFR = "Appel des éléments",
		deDE = "Ruf der Elemente",
		esES = "Llamada de los elementos",
		ruRU = "Зов стихий",
		zhCN = "元素的召唤",
		zhTW = "元素的呼喚",
		ptBR = "Chamado dos Elementos",
		itIT = "Richiamo degli Elementi",
		koKR = "정령의 부름",
	}),
	[66843] = spellNames({
		enUS = "Call of the Ancestors",
		frFR = "Appel des ancêtres",
		deDE = "Ruf der Ahnen",
		esES = "Llamada de los ancestros",
		ruRU = "Зов предков",
		zhCN = "先祖的召唤",
		zhTW = "先祖的呼喚",
		ptBR = "Chamado dos Ancestrais",
		itIT = "Richiamo degli Antenati",
		koKR = "선조의 부름",
	}),
	[66844] = spellNames({
		enUS = "Call of the Spirits",
		frFR = "Appel des esprits",
		deDE = "Ruf der Geister",
		esES = "Llamada de los espíritus",
		ruRU = "Зов духов",
		zhCN = "灵魂的召唤",
		zhTW = "靈魂的呼喚",
		ptBR = "Chamado dos Espíritos",
		itIT = "Richiamo degli Spiriti",
		koKR = "영혼의 부름",
	}),
	[36936] = spellNames({
		enUS = "Totemic Recall",
		frFR = "Rappel totémique",
		deDE = "Totemischer Rückruf",
		esES = "Regreso totémico",
		ruRU = "Возвращение тотемов",
		zhCN = "图腾召回",
		zhTW = "圖騰召回",
		ptBR = "Revocação Totêmica",
		itIT = "Richiamo Totemico",
		koKR = "토템의 귀환",
	}),
	[408490] = spellNames({
		enUS = "Lava Burst",
		frFR = "Explosion de lave",
		deDE = "Lavaeruption",
		esES = { "Ráfaga de lava", "Estallido de lava" },
		ruRU = "Выброс лавы",
		zhCN = "熔岩爆裂",
		zhTW = "熔岩爆發",
		ptBR = "Impacto Lava",
		itIT = "Getto di Lava",
		koKR = "용암 폭발",
	}),
	[408521] = spellNames({
		enUS = "Riptide",
		frFR = "Remous",
		deDE = "Springflut",
		esES = "Mareas vivas",
		ruRU = "Быстрина",
		zhCN = "激流",
		zhTW = "激流",
		ptBR = "Contracorrente",
		itIT = "Flutti",
		koKR = "성난 파도",
	}),
	[408510] = spellNames({
		enUS = "Water Shield",
		frFR = "Bouclier d'eau",
		deDE = "Wasserschild",
		esES = "Escudo de agua",
		ruRU = "Водный щит",
		zhCN = "水之护盾",
		zhTW = "水之盾",
		ptBR = "Escudo de Água",
		itIT = "Scudo d'Acqua",
		koKR = "물의 보호막",
	}),
	[437009] = spellNames({
		enUS = "Totemic Projection",
		frFR = "Projection totémique",
		deDE = "Totemische Projektion",
		esES = "Proyección totémica",
		ruRU = "Проецирование тотема",
		zhCN = "图腾投射",
		zhTW = "圖騰投射",
		ptBR = "Projeção Totêmica",
		itIT = "Proiezione Totemica",
		koKR = "토템 투사",
	}),
	[408341] = spellNames({
		enUS = { "Fire Nova", "Fire Nova Totem" },
		frFR = { "Nova de feu", "Totem Nova de feu" },
		deDE = "Feuernova",
		esES = "Nova de Fuego",
		ruRU = "Кольцо огня",
		zhCN = "火焰新星",
		zhTW = "火焰新星",
		ptBR = "Nova de Fogo",
		itIT = "Nova di Fuoco",
		koKR = "불꽃 회오리",
	}),
	[401502] = spellNames({
		enUS = "Frostfire Bolt",
		frFR = "Éclair de givrefeu",
		deDE = "Frostfeuerblitz",
		esES = "Descarga de Pirofrío",
		ruRU = "Стрела ледяного огня",
		zhCN = "霜火之箭",
		zhTW = "霜火箭",
		ptBR = "Seta de Fogofrio",
		itIT = "Dardo di Fuocogelo",
		koKR = "얼음불꽃 화살",
	}),
	[400640] = spellNames({
		enUS = "Ice Lance",
		frFR = "Javelot de glace",
		deDE = "Eislanze",
		esES = "Lanza de hielo",
		ruRU = "Ледяное копье",
		zhCN = "冰枪术",
		zhTW = "冰霜長矛",
		ptBR = "Lança de Gelo",
		itIT = "Lancia di Ghiaccio",
		koKR = "얼음창",
	}),
	[400574] = spellNames({
		enUS = "Arcane Blast",
		frFR = { "Déflagration des arcanes", "Déflagration des Arcanes" },
		deDE = "Arkanschlag",
		esES = "Explosión Arcana",
		ruRU = "Чародейская вспышка",
		zhCN = "奥术冲击",
		zhTW = "秘法衝擊",
		ptBR = "Impacto Arcano",
		itIT = "Detonazione Arcana",
		koKR = "비전 작렬",
	}),
	[412758] = spellNames({
		enUS = "Incinerate",
		frFR = "Incinérer",
		deDE = "Verbrennen",
		esES = "Incinerar",
		ruRU = "Испепеление",
		zhCN = "烧尽",
		zhTW = "燒盡",
		ptBR = "Incinerar",
		itIT = "Incenerimento",
		koKR = "소각",
	}),
	[980] = spellNames({
		enUS = { "Bane of Agony", "Curse of Agony" },
		frFR = { "Fléau d'agonie", "Malédiction d'agonie" },
		deDE = { "Bann der Pein", "Fluch der Pein" },
		esES = { "Fatalidad de agonía", "Maldición de agonía" },
		ruRU = { "Погибель агонии", "Проклятие агонии" },
		zhCN = { "痛楚灾祸", "痛苦诅咒" },
		zhTW = { "痛苦災禍", "痛苦詛咒" },
		ptBR = { "Ruína da Agonia", "Maldição de Agonia" },
		itIT = { "Flagello dell'Agonia", "Maledizione dell'Agonia" },
		koKR = { "고통의 파멸", "고통의 저주" },
	}),
	[80240] = spellNames({
		enUS = "Bane of Havoc",
		frFR = "Fléau de chaos",
		deDE = "Bann des Chaos",
		esES = "Fatalidad de caos",
		ruRU = "Погибель хаоса",
		zhCN = "浩劫灾祸",
		zhTW = "浩劫災禍",
		ptBR = "Ruína da Devastação",
		itIT = "Flagello del Caos",
		koKR = "대혼란의 파멸",
	}),
	[1311501] = spellNames({
		enUS = "Wrack",
		frFR = "Tourment",
		deDE = "Qual",
		esES = "Suplicio",
		ruRU = "Истязание",
		zhCN = "折磨",
		zhTW = "折磨",
		ptBR = "Suplício",
		itIT = "Tormento",
		koKR = "고문",
	}),
	[713] = spellNames({
		enUS = "Summon Incubus",
		frFR = { "Invocation d'incube", "Invocation d'un incubus" },
		deDE = "Inkubus beschwören",
		esES = "Invocar íncubo",
		ruRU = "Призыв инкуба",
		zhCN = "召唤夜魔",
		zhTW = "召喚夢魔",
		ptBR = "Evocar Íncubo",
		itIT = "Evocazione Incubo",
		koKR = "인큐버스 소환",
	}),
	[414924] = spellNames({
		enUS = "Feral Charge",
		frFR = "Charge farouche",
		deDE = "Wilde Attacke",
		esES = "Carga feral",
		ruRU = "Звериная атака",
		zhCN = "野性冲锋",
		zhTW = "野性衝鋒",
		ptBR = "Investida Feral",
		itIT = "Carica Ferina",
		koKR = "야성의 돌진",
	}),
	[414644] = spellNames({
		enUS = "Lacerate",
		frFR = "Lacérer",
		deDE = "Aufschlitzen",
		esES = "Lacerar",
		ruRU = "Разорвать",
		zhCN = "割伤",
		zhTW = "割裂",
		ptBR = "Lacerar",
		itIT = "Lacerazione",
		koKR = "찢어발기기",
	}),
	[407995] = spellNames({
		enUS = { "Mangle", "Mangle (Bear)", "Mangle (Cat)" },
		frFR = { "Mutilation", "Mutilation (ours)", "Mutilation (félin)" },
		deDE = "Zerfleischen",
		esES = "Destrozar",
		ruRU = "Увечье",
		zhCN = "裂伤",
		zhTW = "裂傷",
		ptBR = "Estraçalhar",
		itIT = "Falciata",
		koKR = "짓이기기",
	}),
	[417141] = spellNames({
		enUS = "Berserk",
		frFR = "Berserk",
		deDE = "Berserker",
		esES = "Rabia",
		ruRU = "Берсерк",
		zhCN = "狂暴",
		zhTW = "狂暴",
		ptBR = "Berserk",
		itIT = "Berserk",
		koKR = "광폭화",
	}),
	[408120] = spellNames({
		enUS = "Wild Growth",
		frFR = "Croissance sauvage",
		deDE = "Wildwuchs",
		esES = "Crecimiento salvaje",
		ruRU = "Буйный рост",
		zhCN = "野性成长",
		zhTW = "野性成長",
		ptBR = "Crescimento Silvestre",
		itIT = "Crescita Selvaggia",
		koKR = "급속 성장",
	}),
	[20577] = spellNames({
		enUS = "Cannibalize",
		frFR = "Cannibalisme",
		deDE = "Kannibalismus",
		esES = "Canibalizar",
		ruRU = "Каннибализм",
		zhCN = "食尸",
		zhTW = "食屍",
		ptBR = "Canibalizar",
		itIT = "Cannibalismo",
		koKR = "시체먹기",
	}),
	[1259813] = spellNames({
		enUS = { "Eureka!", "Eureka" },
		frFR = { "Eureka !", "Eureka!" },
		deDE = { "Heureka!", "Eureka!" },
		esES = "Eureka!",
		ruRU = "Эврика!",
		zhCN = { "尤里卡！", "我知道了！" },
		zhTW = { "尤里卡！", "我想到了！" },
		ptBR = "Eureka!",
		itIT = "Eureka!",
		koKR = "유레카!",
	}),
	[1259810] = spellNames({
		enUS = "Will to Survive",
		frFR = "Volonté de survivre",
		deDE = "Überlebenswille",
		esES = "Voluntad de sobrevivir",
		ruRU = "Воля к жизни",
		zhCN = "求生意志",
		zhTW = "求生意志",
		ptBR = "Vontade de Sobreviver",
		itIT = "Volontà di Sopravvivere",
		koKR = "생존 의지",
	}),
	[1259680] = spellNames({
		enUS = "Elune's Light",
		frFR = "Lumière d'Élune",
		deDE = "Elunes Licht",
		esES = "Luz de Elune",
		ruRU = "Свет Элуны",
		zhCN = "艾露恩之光",
		zhTW = "伊露恩之光",
		ptBR = "Luz de Eluna",
		itIT = "Luce di Elune",
		koKR = "엘룬의 빛",
	}),
	[1259681] = spellNames({
		enUS = "Shatter Curse",
		frFR = "Briser la malédiction",
		deDE = "Fluch zerschmettern",
		esES = "Destrozar maldición",
		ruRU = "Разрушение проклятия",
		zhCN = "粉碎诅咒",
		zhTW = "粉碎詛咒",
		ptBR = "Estilhaçar Maldição",
		itIT = "Spezza Maledizione",
		koKR = "저주 파쇄",
	}),
	[1259682] = spellNames({
		enUS = "Rapid Regeneration",
		frFR = "Régénération rapide",
		deDE = "Rasche Regeneration",
		esES = "Regeneración rápida",
		ruRU = "Стремительное восстановление",
		zhCN = "急速再生",
		zhTW = "急速再生",
		ptBR = "Regeneração Rápida",
		itIT = "Rigenerazione Rapida",
		koKR = "급속 재생",
	}),
}

-- Buffs > 1 min, 60 min, permanents / auras : Défense uniquement, jamais la file de combat.
ns.MAINTENANCE_BUFF_IDS = {}
do
	local P, D, Pr, M, L, Sh, H, W = ns.Spell.Paladin, ns.Spell.Druid, ns.Spell.Priest, ns.Spell.Mage, ns.Spell.Warlock, ns.Spell.Shaman, ns.Spell.Hunter, ns.Spell.Warrior
	local ids = {
		P.BlessingMight, P.BlessingWisdom, P.BlessingKings, P.BlessingSalvation, P.BlessingLight, P.BlessingSanctuary,
		P.DevotionAura, P.RetributionAura, P.ConcentrationAura, P.SanctityAura,
		P.FireResistAura, P.FrostResistAura, P.ShadowResistAura,
		P.RighteousFury,
		D.MarkoftheWild, D.Thorns, D.Moonkin,
		Pr.InnerFire, Pr.PowerWordFortitude, Pr.DivineSpirit, Pr.ShadowProtection, Pr.Shadowform, Pr.VampiricEmbrace,
		M.ArcaneIntellect, M.FrostArmor, M.IceArmor, M.MageArmor, M.AmplifyMagic, M.DampenMagic,
		L.DemonArmor, L.DemonSkin, L.UnendingBreath, L.DetectInvisibility,
		Sh.LightningShield, Sh.WaterShield,
		H.AspectHawk, H.AspectMonkey, H.AspectWild, H.AspectCheetah, H.AspectPack, H.AspectBeast, H.TrueshotAura,
		W.BattleShout,
		25782, 25894, 25898, 25899, 25890, 21562, 21849, 23028, 27681, 27683,
	}
	for _, id in ipairs(ids) do
		if id then
			ns.MAINTENANCE_BUFF_IDS[id] = true
		end
	end
end

-- Soins / HoT : jamais bloqués par une cible hostile (self-cast / retarget).
ns.HEAL_SPELL_IDS = {}
do
	local P, D, Pr, Sh, H = ns.Spell.Paladin, ns.Spell.Druid, ns.Spell.Priest, ns.Spell.Shaman, ns.Spell.Hunter
	local ids = {
		P.HolyLight, P.FlashofLight, P.LayonHands, P.LightsVigil,
		D.HealingTouch, D.Regrowth, D.Rejuvenation, D.Swiftmend, D.Tranquility, D.WildGrowth,
		Pr.FlashHeal, Pr.GreaterHeal, Pr.Heal, Pr.LesserHeal, Pr.Renew, Pr.PrayerofHealing, Pr.PowerWordShield,
		Pr.Penance, Pr.PrayerofMending, Pr.BindingHeal, Pr.DivineGrace, Pr.ContingencyPlan,
		Sh.HealingWave, Sh.LesserHealingWave, Sh.ChainHeal, Sh.HealingStream, Sh.Riptide,
		H.MendPet,
		639, 647, 1026, 1042, 3472, 10328, 10329,
		19939, 19940, 19941, 19942, 19943,
		19968, 19980, 19981, 2800, 10310,
		9472, 9473, 9474, 10915, 10916, 10917,
		10963, 10964, 10965, 2052, 2053, 2055, 6063, 6064,
		332, 547, 913, 939, 959, 8005, 10395, 10396,
		8008, 8010, 10466, 10467, 10468,
		5186, 5187, 5188, 5189, 6778, 8903, 9758, 9888, 9889,
	}
	for _, id in ipairs(ids) do
		if id then
			ns.HEAL_SPELL_IDS[id] = true
		end
	end
end

-- Seconds to wait after a successful cast before suggesting the spell again.
-- Values from Forever 1.60 lab tooltips (Classic Era aura / DoT / HoT / snare
-- durations). Players can override per row in options (opt.hold). 0 disables.
ns.SPELL_HOLD = {}
do
	local P, W, H, R, Pr, Sh, M, L, D =
		ns.Spell.Paladin, ns.Spell.Warrior, ns.Spell.Hunter, ns.Spell.Rogue,
		ns.Spell.Priest, ns.Spell.Shaman, ns.Spell.Mage, ns.Spell.Warlock, ns.Spell.Druid
	local hold = {
		-- Mage
		[M.Frostbolt] = 5, -- chill 40% (rank 1 Forever; higher ranks 6–9s)
		[M.FrostfireBolt] = 9,
		[M.Pyroblast] = 12,
		[M.Flamestrike] = 8,
		[M.FrostNova] = 8,
		[M.ConeofCold] = 6,
		[M.BlastWave] = 6,
		-- Mage Scorch: no aura hold (filler; Improved Scorch is talent-only)
		-- Warlock
		[L.Corruption] = 12,
		[L.Immolate] = 15,
		[L.CurseofAgony] = 24,
		[L.SiphonLife] = 30,
		[L.DrainLife] = 5,
		[L.DrainSoul] = 15,
		[L.Fear] = 10,
		[L.HowlofTerror] = 10,
		[L.DeathCoil] = 3,
		[L.Shadowburn] = 5,
		-- Priest
		[Pr.ShadowWordPain] = 18,
		[Pr.DevouringPlague] = 24,
		[Pr.HolyFire] = 10,
		[Pr.Renew] = 15,
		[Pr.PowerWordShield] = 15, -- Weakened Soul window-ish; shield itself longer
		[Pr.PsychicScream] = 8,
		[Pr.VampiricEmbrace] = 30,
		-- Shaman
		[Sh.FlameShock] = 12,
		[Sh.FrostShock] = 8,
		-- Hunter
		[H.SerpentSting] = 15,
		[H.ViperSting] = 8,
		[H.ScorpidSting] = 20,
		[H.HuntersMark] = 120,
		[H.ConcussiveShot] = 4,
		[H.WingClip] = 10,
		[H.ScatterShot] = 4,
		-- Warrior
		[W.Rend] = 9,
		[W.SunderArmor] = 30,
		[W.Hamstring] = 15,
		[W.ThunderClap] = 10,
		[W.DemoralizingShout] = 30,
		-- Rogue
		[R.Rupture] = 6, -- base 1 CP; player raises with CP
		[R.Garrote] = 18,
		[R.SliceandDice] = 6,
		[R.ExposeArmor] = 30,
		[R.Hemorrhage] = 15,
		[R.Gouge] = 4,
		-- Druid
		[D.Moonfire] = 9,
		[D.InsectSwarm] = 12,
		[D.FaerieFire] = 40,
		[D.FaerieFireFeral] = 40,
		[D.Rake] = 9,
		[D.Rip] = 12,
		[D.Lacerate] = 15,
		[D.Rejuvenation] = 12,
		[D.Regrowth] = 21,
		[D.DemoralizingRoar] = 30,
		-- Paladin seals are maintained via nobuff; short CC / judgements
		[P.HammerofJustice] = 3,
		[P.Consecration] = 8,
	}
	for id, sec in pairs(hold) do
		if id and type(sec) == "number" and sec > 0 then
			ns.SPELL_HOLD[id] = sec
		end
	end
end

-- Secours si GetSpellBaseCooldown ne renvoie rien. Le client prime dès qu'il répond.
-- Valeurs Classic Era (secondes). Les horions partagent un seul temps de recharge.
do
	local P = ns.Spell.Paladin
	local W = ns.Spell.Warrior
	local H = ns.Spell.Hunter
	local R = ns.Spell.Rogue
	local Pr = ns.Spell.Priest
	local Sh = ns.Spell.Shaman
	local M = ns.Spell.Mage
	local L = ns.Spell.Warlock
	local D = ns.Spell.Druid
	ns.COOLDOWNS = {
		[P.Judgement] = 8,
		[P.HammerofJustice] = 60,
		[P.HammerofWrath] = 6,
		[P.Exorcism] = 15,
		[P.Consecration] = 8,
		[P.HolyShock] = 15,
		[P.HolyWrath] = 60,
		[P.CrusaderStrike] = 6,
		[P.HolyStrike] = 12,
		[P.LightsVigil] = 60,
		[P.VoiceOfTruth] = 60,
		[P.TemplarsBulwark] = 60,
		[P.SwiftJudgement] = 60,
		[P.LayonHands] = 3600,
		[P.DivineShield] = 300,
		[P.DivineProtection] = 300,
		[W.MortalStrike] = 6,
		[W.Bloodthirst] = 6,
		[W.Whirlwind] = 10,
		[W.Revenge] = 5,
		[W.ShieldSlam] = 6,
		[W.ThunderClap] = 4,
		[W.ShieldBlock] = 5,
		[W.Pummel] = 10,
		[W.ShieldBash] = 12,
		[W.Intercept] = 30,
		[W.Bloodrage] = 60,
		[W.BerserkerRage] = 30,
		[W.SweepingStrikes] = 30,
		[W.DeathWish] = 180,
		[W.Taunt] = 10,
		[W.MockingBlow] = 120,
		[W.Disarm] = 60,
		[W.Retaliation] = 1800,
		[W.Recklessness] = 1800,
		[W.ShieldWall] = 1800,
		[W.LastStand] = 480,
		[W.SpearingStrike] = 20,
		[W.VictoryRush] = 20,
		[H.AimedShot] = 6,
		[H.MultiShot] = 10,
		[H.ArcaneShot] = 6,
		[H.ConcussiveShot] = 12,
		[H.Counterattack] = 5,
		[H.Intimidation] = 60,
		[H.FeignDeath] = 30,
		[H.RapidFire] = 300,
		[H.BestialWrath] = 120,
		[H.Deterrence] = 300,
		[H.WyvernSting] = 120,
		[H.StriderKick] = 8,
		[H.SniperShot] = 20,
		[H.ScatterShot] = 30,
		[H.HydraShot] = 12,
		[H.Lacerate] = 6,
		[H.TranquilizingShot] = 20,
		[H.EnchantedFlare] = 30,
		[H.Flare] = 15,
		[H.DistractingShot] = 8,
		[R.Kick] = 10,
		[R.Gouge] = 10,
		[R.Riposte] = 6,
		[R.GhostlyStrike] = 20,
		[R.BladeFlurry] = 120,
		[R.AdrenalineRush] = 300,
		[R.Evasion] = 300,
		[R.Sprint] = 300,
		[R.Vanish] = 300,
		[R.Mutilate] = 6,
		[R.Venom] = 20,
		[R.Preparation] = 600,
		[Pr.MindBlast] = 8,
		[Pr.PsychicScream] = 30,
		[Pr.Fade] = 30,
		[Pr.Silence] = 45,
		[Pr.InnerFocus] = 180,
		[Pr.PowerInfusion] = 180,
		[Pr.Chastise] = 30,
		[Pr.ConfoundingFlash] = 30,
		[Pr.DarkSacrifice] = 120,
		[Pr.DivineGrace] = 600,
		[Pr.ContingencyPlan] = 15,
		[Pr.Penance] = 8,
		[Pr.PrayerofMending] = 10,
		[Pr.ShadowWordDeath] = 12,
		[Sh.EarthShock] = 6,
		[Sh.FlameShock] = 6,
		[Sh.FrostShock] = 6,
		[Sh.ChainLightning] = 6,
		[Sh.Stormstrike] = 20,
		[Sh.ElementalMastery] = 180,
		[Sh.NaturesSwiftness] = 180,
		[Sh.LavaBurst] = 8,
		[Sh.Riptide] = 6,
		[Sh.CalloftheElements] = 180,
		[Sh.CalloftheAncestors] = 180,
		[Sh.CalloftheSpirits] = 180,
		[Sh.TotemicRecall] = 6,
		[Sh.TotemicProjection] = 60,
		[Sh.FireNova] = 10,
		[M.FireBlast] = 8,
		[M.ConeofCold] = 10,
		[M.BlastWave] = 30,
		[M.FrostNova] = 25,
		[M.Counterspell] = 30,
		[M.Blink] = 15,
		[M.Combustion] = 180,
		[M.PresenceofMind] = 180,
		[M.ArcanePower] = 180,
		[M.Evocation] = 480,
		[M.IceBlock] = 300,
		[L.Conflagrate] = 10,
		[L.Shadowburn] = 15,
		[L.DeathCoil] = 120,
		[L.HowlofTerror] = 40,
		[D.Swiftmend] = 15,
		[D.Bash] = 60,
		[D.Barkskin] = 60,
		[D.FeralCharge] = 15,
		[D.Enrage] = 60,
		[D.FrenziedRegen] = 180,
		[D.NaturesSwiftness] = 180,
		[D.Innervate] = 360,
		[D.Tranquility] = 300,
		[D.FeralChargeCat] = 15,
		[D.Berserk] = 180,
		[D.WildGrowth] = 6,
		[D.MangleCat] = 6,
		[D.MangleBear] = 6,
	}
	ns.COOLDOWN_GROUPS = {
		{ seconds = 6, ids = { Sh.EarthShock, Sh.FlameShock, Sh.FrostShock } },
	}
	ns.COMBO_BUILDERS = {
		[R.SinisterStrike] = true,
		[R.Hemorrhage] = true,
		[R.GhostlyStrike] = true,
		[R.Mutilate] = true,
		[R.Backstab] = true,
		[D.Claw] = true,
		[D.Shred] = true,
		[D.MangleCat] = true,
	}
end
